"""stock_daily_bars_and_stock_feature_columns

Revision ID: 56997912b257
Revises: 600ad86b1e31
Create Date: 2026-06-04 22:05:50.551012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56997912b257'
down_revision: Union[str, Sequence[str], None] = '600ad86b1e31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_daily_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('change_rate', sa.Float(), nullable=True),
    sa.Column('change_amount', sa.Float(), nullable=True),
    sa.Column('quote_source', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'trade_date', name='uq_stock_daily_bars_stock_date')
    )
    op.create_index(op.f('ix_stock_daily_bars_id'), 'stock_daily_bars', ['id'], unique=False)
    op.add_column('market_reports', sa.Column('company_reports', sa.JSON(), nullable=True))
    op.add_column('market_reports', sa.Column('data_collected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('market_reports', sa.Column('report_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stocks', sa.Column('trade_date', sa.Date(), nullable=True))
    op.alter_column('stocks', 'price', new_column_name='current_price', existing_type=sa.Float())
    op.add_column('stocks', sa.Column('day_open', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('day_high', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('day_low', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('day_close', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('prev_close', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('change_amount', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('volume', sa.BigInteger(), nullable=True))
    op.add_column('stocks', sa.Column('volume_change_rate', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('day_range_pct', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('quote_source', sa.String(), nullable=True))
    op.add_column('stocks', sa.Column('data_collected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('stocks', sa.Column('close_max_5d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('close_min_5d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('close_avg_5d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('high_max_5d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('low_min_5d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('volume_avg_5d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('close_max_20d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('close_min_20d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('close_avg_20d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('high_max_20d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('low_min_20d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('volume_avg_20d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('close_max_60d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('close_min_60d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('close_avg_60d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('high_max_60d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('low_min_60d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('volume_avg_60d', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('vs_avg_20d_pct', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('vs_60d_high_pct', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('vs_60d_low_pct', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('eps', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('beta', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('fifty_two_week_high', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('fifty_two_week_low', sa.Float(), nullable=True))
    op.add_column('stocks', sa.Column('avg_volume_10d', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stocks', 'current_price', new_column_name='price', existing_type=sa.Float())
    op.drop_column('stocks', 'avg_volume_10d')
    op.drop_column('stocks', 'fifty_two_week_low')
    op.drop_column('stocks', 'fifty_two_week_high')
    op.drop_column('stocks', 'beta')
    op.drop_column('stocks', 'eps')
    op.drop_column('stocks', 'vs_60d_low_pct')
    op.drop_column('stocks', 'vs_60d_high_pct')
    op.drop_column('stocks', 'vs_avg_20d_pct')
    op.drop_column('stocks', 'volume_avg_60d')
    op.drop_column('stocks', 'low_min_60d')
    op.drop_column('stocks', 'high_max_60d')
    op.drop_column('stocks', 'close_avg_60d')
    op.drop_column('stocks', 'close_min_60d')
    op.drop_column('stocks', 'close_max_60d')
    op.drop_column('stocks', 'volume_avg_20d')
    op.drop_column('stocks', 'low_min_20d')
    op.drop_column('stocks', 'high_max_20d')
    op.drop_column('stocks', 'close_avg_20d')
    op.drop_column('stocks', 'close_min_20d')
    op.drop_column('stocks', 'close_max_20d')
    op.drop_column('stocks', 'volume_avg_5d')
    op.drop_column('stocks', 'low_min_5d')
    op.drop_column('stocks', 'high_max_5d')
    op.drop_column('stocks', 'close_avg_5d')
    op.drop_column('stocks', 'close_min_5d')
    op.drop_column('stocks', 'close_max_5d')
    op.drop_column('stocks', 'data_collected_at')
    op.drop_column('stocks', 'quote_source')
    op.drop_column('stocks', 'day_range_pct')
    op.drop_column('stocks', 'volume_change_rate')
    op.drop_column('stocks', 'volume')
    op.drop_column('stocks', 'change_amount')
    op.drop_column('stocks', 'prev_close')
    op.drop_column('stocks', 'day_close')
    op.drop_column('stocks', 'day_low')
    op.drop_column('stocks', 'day_high')
    op.drop_column('stocks', 'day_open')
    op.drop_column('stocks', 'trade_date')
    op.drop_column('market_reports', 'report_generated_at')
    op.drop_column('market_reports', 'data_collected_at')
    op.drop_column('market_reports', 'company_reports')
    op.drop_index(op.f('ix_stock_daily_bars_id'), table_name='stock_daily_bars')
    op.drop_table('stock_daily_bars')
    # ### end Alembic commands ###
